### ISSUE TITLE
Send ASCII commands to terminal?

### ISSUE THREAD

**Issue by EtnasSoft** [ArminJo/ATtinySerialOut#1]
Hi, great work!
Is it possible to send from your library a sequence for clear the terminal?

I want something similar to:

```
Serial.write(27);       //ESC command
Serial.print("[2J");    //clear screen command
Serial.write(27);
Serial.print("[H");     //cursor to home command 
```

But I can't make it work.
How can I achieve it?

Regards!

**Comment by ArminJo** [comment]
Hi,
of course you can send any escape sequences, but it depends on the terminal if it accepts these sequences!
Good Luck
