### ISSUE TITLE
Add a way to change the tx pin programmatically

### ISSUE THREAD

**Issue by jbaumann** [ArminJo/ATtinySerialOut#2]
Enhancement:
It would be very nice to have a way to change the TX pin without having to change the header file itself e.g., by providing it as a parameter to the initTXPin() method.

**Comment by ArminJo** [comment]
I totally agree 👍 
If you have any idea, please tell me!

**Comment by jbaumann** [comment]
One way to do it would be to introduce a variable that holds the pin and is set during the initialization with an additional parameter. This would need additional space.
Another way would be to move every access to the pin to the header file (and you have to watch out that the compiler does not inline these accesses). This would mean additional function calls and thus overhead.
The third way would be to move the whole implementation tot the header file. This would have no impact on space or time but would make the code a little less readable.

**Comment by ArminJo** [comment]
> The third way would be to move the whole implementation tot the header file. This would have no impact on space or time but would make the code a little less readable.

Why not?
See ATtinySerialOutExample.cpp.

**Comment by marko-pi** [comment]
I agree with @jbaumann that it would be nice if TX could be changed **without interfering with the library** (editing .h, deleting a file...)

If this is not possible, does anyone know of another avr library that supports TX and allows changing TX without interfering with the library? For me this is more important than the brevity of the library.

Thanks!

**Comment by ArminJo** [comment]
Can [this](https://github.com/ArminJo/ATtinySerialOut/blob/6c710f10e94671543917b02598c1e77cdff27068/examples/ATtinySerialOutExample/ATtinySerialOutExample.ino#L36) be a way for you?
You only must change comments in the code and delete a library file. ( or use a professional IDE like [Sloeber](https://eclipse.baeyens.it/))

**Comment by marko-pi** [comment]
@ArminJo I know about that.  The point is _deleting_ a file... you have to find the location of libraries, which are different for every system.

**Comment by ArminJo** [comment]
### Modifying compile options with Arduino IDE
First, use *Sketch > Show Sketch Folder (Ctrl+K)*.
If you did not yet stored the example as your own sketch, then you are instantly in the right library folder.
Otherwise you have to navigate to the parallel `libraries` folder and select the library you want to access.
In both cases the library files itself are located in the `src` directory.

Or you have a look in the build log 😀

**Comment by marko-pi** [comment]
Whatever, it is messy.

If it is not possible to adjust library (or perhaps add ATtinySerialOutPin.cpp / ATtinySerialOutPin.h), could you at least advise me if something like SoftwareSerial mySerial(12, 4) would be OK?  Redirecting RX to unexisting pin?

**Comment by marko-pi** [comment]
One question.  I am not a computer engineer so it takes me a bit more to figure something out.

If you renamed ATtinySerialOut.cpp.h to, say, ATtinySerialOutPin.h, one could control TX pin without deleting ATtinySerialOut.cpp?  Like this:

#define TX_PIN 2
#include <ATtinySerialOutPin.h>

**Comment by ArminJo** [comment]
You nag! And you won!
Please install the current repository as library and you must not longer delete the .cpp file any more to specify TX pin.
See ATtinySerialOutExample example.

**Comment by marko-pi** [comment]
Thanks in my name and name of other potential users!  This means that my project https://github.com/marko-pi/MPED-DIY is finally finished.  I have included those new two files until they get distributed by Arduino IDE ecosystem and I can now start writing instructions.

I apologise for nagging and I hope it did not take too much time.  Best regards to Germany.
