### ISSUE TITLE
error: operator '||' has no right operand

### ISSUE THREAD

**Issue by Nishh** [ArminJo/ATtinySerialOut#9]
Error:
https://justpaste.it/7cax9

System: Windows 10 64 bit
Arduino version: latest (1.8.19)
ATtinySerialOut version: latest (2.0.0)

**Comment by ArminJo** [comment]
Which core???

**Comment by Nishh** [comment]
I was trying to use this: https://github.com/Arduino-IRremote/Arduino-IRremote

Cannot compile SimpleReceiver example for MH-ET Tiny88 board (ATtiny88)

I'm new to this and not sure what is "core"

**Comment by Nishh** [comment]
I was trying to use this: https://github.com/Arduino-IRremote/Arduino-IRremote

Cannot compile SimpleReceiver example for MH-ET Tiny88 board (ATtiny88)

I'm new to this and not sure what is "core"

**Comment by Nishh** [comment]
Tried MinimalReceiver, compiled and uploaded without a problem.

It responds with led but not sure if it gets the right input because I can't use serial monitor.
(not working for some reason)

**Comment by Nishh** [comment]
Read output with SoftwareSerial and everything works.

**Comment by ArminJo** [comment]
Thank you very much for reporting 🥇 
I also updated the macro, which throws the error. 😀
